# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('email_address', models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator])),
                ('joined_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
    ]
