# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('joined_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
    ]
