# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20171025_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistsubscriber',
            name='id',
        ),
        migrations.AlterField(
            model_name='mailinglistsubscriber',
            name='email_address',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator]),
        ),
    ]
