# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator]),
        ),
    ]
