# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 05:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2017, 11, 5, 5, 21, 11, 894832), verbose_name='publish time')),
                ('last_modified_time', models.DateTimeField(null=True, verbose_name='last modified time')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='subtitle')),
                ('content', models.TextField(verbose_name='content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
