# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 6, 6, 50, 253434, tzinfo=utc), verbose_name='publish time'),
        ),
    ]
