# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20171105_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time'),
        ),
    ]
