# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_auto_20171106_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
    ]
