# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_auto_20171106_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
